### ISSUE TITLE
El Signup no funciona y ya no puedo ver nada más, esta es la exception que me encuentro en el Logcat

### ISSUE THREAD

**Issue by Alqueraf** [ArnauAguilarEmanuel/GameCompanion#1]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.marcsolis.gamecompanion, PID: 5023
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.marcsolis.gamecompanion.activity.RegisterActivity$onCreate$1$7.onSuccess(RegisterActivity.kt:138)
        at com.marcsolis.gamecompanion.activity.RegisterActivity$onCreate$1$7.onSuccess(RegisterActivity.kt:25)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ArnauAguilarEmanuel** [comment]
Buenas Alex, 
Estamos intentando replicar el error pero no somos capazes, te paso por correo un video para que veas que a nosotros nos funciona bien en nuestros equipos y en los móviles.Te adjuntamos además la apk y un zip con el proyecto y más información para ver como lo podemos evaluar.
